-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, NVL(SUM(O.SALES_AMOUNT),0) * P.PRICE AS SALES
FROM PRODUCT P LEFT JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE, P.PRICE
ORDER BY SALES DESC, PRODUCT_CODE

-- SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT) * P.PRICE AS SALES