-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD b left join USED_GOODS_USER u
on b.WRITER_ID= u.USER_ID
where STATUS = 'DONE'
group by u.USER_ID, u.NICKNAME
having TOTAL_SALES >= 700000
order by TOTAL_SALES
